
lane :tests do
    
    clear_derived_data(derived_data_path: ".fastlane/DerivedData/")

    scan(
        workspace: "LayoutKit.xcworkspace",
        scheme: "LayoutKit-iOS",
        devices: [
            "iPhone XS"
            #"iPhone XS (12.0)", 
            #"iPhone X (11.4)", 
            #"iPhone 7 Plus (10.3.1)", 
            #"iPhone 6 (9.0)"
        ],
        clean: true,
        code_coverage: true,
        derived_data_path: ".fastlane/DerivedData/"
    )

end

lane :test do
    
    desc "Run Tests"
    scan(
        workspace: "LayoutKit.xcworkspace",
        scheme: "LayoutKit-iOS",
        devices: [
            "iPhone XS (12.0)", 
            "iPhone X (11.4)", 
            "iPhone 7 Plus (10.3.1)", 
            "iPhone 6 (9.0)"
        ],
        clean: true,
        code_coverage: true
    )

end

lane :report_test_coverage do
    
    desc "Run Tests"
    xcov(
        workspace: "LayoutKit.xcworkspace",
        scheme: "LayoutKit-iOS",
    )

end

lane :coverage_slather do

    slather(
        proj: "LayoutKit.xcodeproj",
        workspace: "LayoutKit.xcworkspace",
        scheme: "LayoutKit-iOS",
        html: true,
        output_directory: "SlatherCoverage/",
        build_directory: ".fastlane/DerivedData/"
    )

end

lane :carthage_update do 

    carthage(
        command: "update",
        derived_data: ".fastlane/DerivedData/",
        platform: "iOS",
        cache_builds: true,
        configuration: "Release",
        log_path: ".fastlane/Carthage/carthage.log"
    )

end 

lane :pod_install do 

    cocoapods(
        podfile: "./Podfile"
    )

end